# Custom Language File for Launcher Customizer

[ejs.app]
title = "Rustolia Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/ArtichautDev/RustoliaLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/rustolia"

[ejs.settings]
sourceGithubLink = "https://github.com/ArtichautDev/RustoliaLauncher"
supportLink = "https://github.com/ArtichautDev/RustoliaLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Rustolia"
welcomeDescription = "Bienvenue sur Rustolia, un serveur Minecraft où l’univers mythologique de la Grèce antique prend vie à travers des mécaniques de jeu innovantes et des contenus sur mesure. Plongez dans un monde fantastique rempli de défis épiques, de créatures légendaires et de secrets à découvrir."
welcomeDescCTA = "Vous êtes juste à quelques clics de Rustolia."
